#任务执行类型
Task_Type_List: ['getTaskPrize','getLuckyPrize','completeTask','getThreeTasklist','getAllTasklist','upGameTask','share']

#type_1 :邀请新用户体验《崩坏：星穹铁道》云玩 completeTask share
#type_3 :每日体验《崩坏：星穹铁道》 completeTask 
#type_4 :每日签到领快爆独家游戏礼包 completeTask 
#type_18 :开启快爆通知权限 completeTask upGameTask
#type_11 :体验《崩坏：星穹铁道》云玩 completeTask upGameTask

#url为空
#‘RereadPlant’检查生长状况

#url为daily
daily:
  DailyApp: ['DailyApp', 'DailyAppLing']
  DailyGameCateJump: ['DailyGameCateJump','DailyGameCateLing']
  #分享奖励
  DailyShare: ['DailyShare', 'DailyShareCallback', 'DailyShareLing']
  #预约奖励需先预约, 无法实现
  DailyYuyueLing: ['DailyYuyueLing']
  #先用第二个获取答案再进行回答，回答时请求体需加入‘option’，其值为中文答案
  DailyDati: ['DailyDati', 'DailyDatiAnswer', 'DailyDatiAnswer', 'DailyDatiLing']
  DailyToH5Url: ['DailyToH5Url', 'DailyToH5UrlLing']
  DailyDownGameLing: ['DailyGamePlay', 'DailyDownGameCheck', 'DailyDownGameLing']
  DailySmallGame: ['DailySmallGame', 'DailySmallGameLing'] 

#url为ycx
ycx:
  YcxDownGameLing: ['YcxGamePlay', 'YcxDownGameCheck', 'YcxDownGameLing']
  YcxToH5Url: ['YcxToH5Url', 'YcxToH5UrlLing']
  #等待五分钟

#url为plant
plant: ['plant', 'Harvest']
#‘plant’为种植种子
#‘Harvest’为收获
exchange: {
  unlogin_detail: {"a": 'init', "c": 'Detail'},
  login_detail: {"a": 'init', "c": 'Detail'},
  obtain_detail: {"a": 'checkOrder', "c": 'OrderVirtual'},
  exchange: {"a": 'createOrder', "c": 'OrderVirtual'},
  share: {"a": 'shareForBmh', "c": 'UserDetail'}
}
#设备的数量
device_num: 2
#活动目录网页
ac_web: ['https://huodong3.i3839.com/n/hykb/qdjh/index.php', 'https://huodong2.3839.com/flzx/index.html']
#活动网页关键词
keyword: universal
